name: push

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '3.1.201'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - run: dotnet run -p build/build.csproj -- test
